import type { DatabaseColumn } from '../../types.js';

export const generatedHeader = [
    '# This file was generated by db-man.',
    '# Update the configured database schema repository, then run `db-man generate` to refresh it.',
    '',
].join('\n');

export const sqlalchemyImportOrder = [
    'ARRAY',
    'BigInteger',
    'Boolean',
    'Column',
    'Date',
    'DateTime',
    'Float',
    'Integer',
    'JSON',
    'LargeBinary',
    'Numeric',
    'SmallInteger',
    'String',
    'Text',
    'Time',
    'Uuid',
    'func',
    'text',
];

const pythonKeywords = new Set([
    'False',
    'None',
    'True',
    'and',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'class',
    'continue',
    'def',
    'del',
    'elif',
    'else',
    'except',
    'finally',
    'for',
    'from',
    'global',
    'if',
    'import',
    'in',
    'is',
    'lambda',
    'nonlocal',
    'not',
    'or',
    'pass',
    'raise',
    'return',
    'try',
    'while',
    'with',
    'yield',
]);

export function isEditableColumn(column: DatabaseColumn): boolean {
    return !column.primaryKey && !['created_at', 'updated_at', 'deleted_at'].includes(column.name);
}

export function isSequenceDefault(defaultValue: string | undefined): boolean {
    return Boolean(defaultValue && /\bnextval\s*\(/i.test(defaultValue));
}

export function isNowDefault(defaultValue: string | undefined): boolean {
    return Boolean(defaultValue && /^(now\(\)|CURRENT_TIMESTAMP)$/i.test(defaultValue.trim()));
}

export function parseLiteralDefault(defaultValue: string | undefined): string | undefined {
    if (!defaultValue || isSequenceDefault(defaultValue) || isNowDefault(defaultValue)) {
        return undefined;
    }

    const normalizedDefault = defaultValue.trim().replace(/::[A-Za-z_][\w]*(?:\[\])?/g, '');

    if (/^true$/i.test(normalizedDefault)) {
        return 'True';
    }

    if (/^false$/i.test(normalizedDefault)) {
        return 'False';
    }

    if (/^-?\d+(?:\.\d+)?$/.test(normalizedDefault)) {
        return normalizedDefault;
    }

    const stringMatch = normalizedDefault.match(/^'(.*)'$/s);
    if (stringMatch) {
        return `"${escapePythonString(stringMatch[1].replace(/''/g, "'"))}"`;
    }

    return undefined;
}

export function normalizeSqlType(sqlType: string): string {
    return sqlType.trim().replace(/\s+/g, ' ').toLowerCase();
}

export function extractTypeNumbers(normalizedType: string): number[] {
    const numberMatch = normalizedType.match(/\(([^)]+)\)/);
    if (!numberMatch) {
        return [];
    }

    return numberMatch[1]
        .split(',')
        .map((numberPart) => Number.parseInt(numberPart.trim(), 10))
        .filter((numberPart) => Number.isFinite(numberPart));
}

export function singularize(value: string): string {
    if (value.endsWith('analyses')) {
        return `${value.slice(0, -8)}analysis`;
    }

    if (value.endsWith('analysis')) {
        return value;
    }

    if (value.endsWith('ies')) {
        return `${value.slice(0, -3)}y`;
    }

    if (value.endsWith('ses') || value.endsWith('xes') || value.endsWith('ches') || value.endsWith('shes')) {
        return value.slice(0, -2);
    }

    if (value.endsWith('s') && !value.endsWith('ss')) {
        return value.slice(0, -1);
    }

    return value;
}

export function toClassName(value: string): string {
    return value
        .split(/[^A-Za-z0-9]+/)
        .filter(Boolean)
        .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
        .join('');
}

export function toSnakeCase(value: string): string {
    return value
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
        .replace(/[^A-Za-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .toLowerCase();
}

export function toPythonIdentifier(value: string): string {
    const identifier = toSnakeCase(value);
    const safeIdentifier = /^\d/.test(identifier) ? `_${identifier}` : identifier;

    if (pythonKeywords.has(safeIdentifier)) {
        return `${safeIdentifier}_`;
    }

    return safeIdentifier;
}

export function orderImports(imports: Set<string>, preferredOrder: string[]): string[] {
    const preferredImports = preferredOrder.filter((importName) => imports.has(importName));
    const remainingImports = [...imports]
        .filter((importName) => !preferredOrder.includes(importName))
        .sort((firstImport, secondImport) => firstImport.localeCompare(secondImport));

    return [...preferredImports, ...remainingImports];
}

export function escapePythonString(value: string): string {
    return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export function ensureTrailingNewline(value: string): string {
    return value.endsWith('\n') ? value : `${value}\n`;
}
